Update to latest netsec-ethz/scion:scionlab, hellodrkey to DRKey v2
netsec-ethz/scion-apps pull request #226
Opened 2022-04-22 13:17 UTC by matzf

Note: the hellodrkey example now uses `grpc` directly which is a bit annoying as it now needs to be listed in the `go.mod` file -- the `_examples` are (intentionally) ignored for e.g. `go mod tidy`, so this will be removed by running the tool and needs to be manually kept in. The "correct" solution seems to be to have an `_examples/go.mod` file to include the dependencies used exclusively by the examples -- this appears to be a bit of a hassle on its own though, but possibly go-1.18's workspaces might make this somewhat usable.

2022-05-03 15:33 UTC, juagargi requested changes
I think it makes sense to have now a `go.mod` file in `_examples/hellodrkey` and use workspaces whenever we move to 1.18.
Otherwise as you say, a simple `go mod tidy` will break our `go.mod`.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-:-N19Y5PA-7090Q4J_DWn:b-inugov)* status: all files reviewed, 5 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`_examples/hellodrkey/hellodrkey.go` line 43 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19X0qp0fruorrUnnh2:-N19X0qp0fruorrUnnh3:b-rid0n6) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L43)):*
> ```Go
> 
> func NewClient(sciondPath string) Client {
> 	ctx, cancelF := context.WithTimeout(context.Background(), time.Second)
> ```

what about receiving the context as argument?
___
*[`_examples/hellodrkey/hellodrkey.go` line 53 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19XGZg4_Q9FkUHHg9u:-N19XGZg4_Q9FkUHHg9v:b-wijg2n) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L53)):*
> ```Go
> 
> func (c Client) HostHostKey(meta drkey.HostHostMeta) drkey.HostHostKey {
> 	ctx, cancelF := context.WithTimeout(context.Background(), 2*time.Second)
> ```

receive the context?
___
*[`_examples/hellodrkey/hellodrkey.go` line 67 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19XJcZ-knPV8BsMYRs:-N19XJcZ-knPV8BsMYRt:b-wijg2n) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L67)):*
> ```Go
> 
> func NewServer(sciondPath string) Server {
> 	ctx, cancelF := context.WithTimeout(context.Background(), time.Second)
> ```

receive the context?
___
*[`_examples/hellodrkey/hellodrkey.go` line 81 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19XQFuAofnfZx9h3yQ:-N19XQFuAofnfZx9h3yR:b-iyt3gf) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L81)):*
> ```Go
> // from in the control server's configuration:
> //
> // Example gen/ASff00_0_111/cs1-ff00_0_111-1.toml:
> ```

It is already documented in the README. Do we need to write it twice?
___
*[`_examples/hellodrkey/hellodrkey.go` line 96 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19WPbhDrab6NA_8UiL:-N19WPbhDrab6NA_8UiM:b-jx4y2e) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L96)):*
> ```Go
> 
> 	// Contact CS directly for SV
> 	conn, err := grpc.DialContext(ctx, cs, grpc.WithInsecure())
> ```

Why is the secret value a special case? I.e. why is there no API in the daemon to get it?
Applications query for host to/from host/AS keys, but also for secret values (e.g. a DNS server)


<!-- Sent from Reviewable.io -->

2022-05-04 07:45 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226)* status: all files reviewed, 5 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`_examples/hellodrkey/hellodrkey.go` line 43 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19X0qp0fruorrUnnh2:-N1Cujhy6BjFvmVmY6jL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L43)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

what about receiving the context as argument?
</blockquote></details>

Done.
___
*[`_examples/hellodrkey/hellodrkey.go` line 53 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19XGZg4_Q9FkUHHg9u:-N1CulQE1qYd0VajW85r:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L53)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

receive the context?
</blockquote></details>

Done.
___
*[`_examples/hellodrkey/hellodrkey.go` line 67 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19XJcZ-knPV8BsMYRs:-N1Cuj9a4Ym0v0Ppusa4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L67)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

receive the context?
</blockquote></details>

Done.
___
*[`_examples/hellodrkey/hellodrkey.go` line 81 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19XQFuAofnfZx9h3yQ:-N1Cui_jALfip2wVRxjW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L81)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

It is already documented in the README. Do we need to write it twice?
</blockquote></details>

Done.
___
*[`_examples/hellodrkey/hellodrkey.go` line 96 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19WPbhDrab6NA_8UiL:-N1CttMOE-pZhqpyy1H4:brl8b0k) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L96)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Why is the secret value a special case? I.e. why is there no API in the daemon to get it?
Applications query for host to/from host/AS keys, but also for secret values (e.g. a DNS server)
</blockquote></details>

Because the SV is more sensitive than ordinary host keys we don't want any more components to be involved than necessary. The daemon can also not add any useful caching for this, as the SVs are only accessed infrequently and must be kept in the applications to get reasonable performance.
The SV is not the only special case -- the Lvl1 keys issued by remote ASes for a specific protocol (i.e. the "slow" Lvl1 keys) are also accessible via the same mechanism for authorized applications/hosts.
I also expect that fetching these will be made "more special" e.g. by requiring TLS with client certificates.

Perhaps we could at some point wrap the grpc calls in a library function though.


<!-- Sent from Reviewable.io -->

2022-05-04 08:28 UTC, JordiSubira approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-:-N1DAm7XDfgTWloiFfgX:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`_examples/hellodrkey/hellodrkey.go` line 96 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19WPbhDrab6NA_8UiL:-N1D7Dg98Ztr0DXyLaFr:b-ayvfq8) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L96)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Because the SV is more sensitive than ordinary host keys we don't want any more components to be involved than necessary. The daemon can also not add any useful caching for this, as the SVs are only accessed infrequently and must be kept in the applications to get reasonable performance.
The SV is not the only special case -- the Lvl1 keys issued by remote ASes for a specific protocol (i.e. the "slow" Lvl1 keys) are also accessible via the same mechanism for authorized applications/hosts.
I also expect that fetching these will be made "more special" e.g. by requiring TLS with client certificates.

Perhaps we could at some point wrap the grpc calls in a library function though.
</blockquote></details>

I will jot this down in the pending task for future iterations of the DRKey implementation.


<!-- Sent from Reviewable.io -->

2022-05-04 08:49 UTC, juagargi requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

___
*[`_examples/hellodrkey/hellodrkey.go` line 96 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19WPbhDrab6NA_8UiL:-N1DDtBi-bx6o7N9SEre:b-vegvuq) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L96)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I will jot this down in the pending task for future iterations of the DRKey implementation.
</blockquote></details>

A library call will be sufficient, the call does not need to go through the daemon.


<!-- Sent from Reviewable.io -->

2022-05-06 13:14 UTC, juagargi requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-06 13:16 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

___
*[`_examples/hellodrkey/hellodrkey.go` line 96 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-N19WPbhDrab6NA_8UiL:-N1OT2v6AMJP-syZ-D9e:byzchkn) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/72f13c4b8fd0cd77b299869cb0e17ce6741471f2/_examples/hellodrkey/hellodrkey.go#L96)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

A library call will be sufficient, the call does not need to go through the daemon.
</blockquote></details>

I like the minimalistic approach. I use the same grpc call in LightningFilter with a configurable address for the control service (DRKey service) instead of calling SVCInfo on the daemon.


<!-- Sent from Reviewable.io -->

2022-05-06 13:16 UTC, fstreun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-:-N1OVxkH285h2-6yYX1h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-05-09 08:41 UTC, juagargi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226#-:-N1bycEk2TyxLHGhOaHe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-09 10:07 UTC, juagargi approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/226)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-10 08:56 UTC, merged