Add path selector context and explicit path query
netsec-ethz/scion-apps pull request #260
Opened 2024-11-24 13:42 UTC by lschulz

Adds a context pointer to the path selector's Path() method that allows applications to pass arbitrary context data to their custom path selector. Currently Path() has to select a path without knowing anything about the packet it picks a path for. The context can provide additional information, e.g., whether the packet is urgent or not.

Adds an exported function for querying paths to a particular destination AS. This function was missing before, making it very hard to send a packet to a new destination on a ListenConn.

Adds a getter for the size of a path in the dataplane. The path size can be used with the MTU metadata to approximate the maximum payload size per packet.

Other changes:
- Return an error if SCION host context initialization fails (e.g., because one forgot to set SCION_DAEMON_ADDRESS). Previously PAN terminated the application in this case even though a connection error is very likely recoverable. Returning an error to the application is especially important for GUI apps that do not have a terminal PAN could print anything to.

2024-11-25 09:47 UTC, JordiSubira requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/260)* status: all files reviewed, 11 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/pan/udp_listen.go` line 57 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgX4S0vRXujwcMY3-:-OCXgX4S0vRXujwcMY30:b-87nk97) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/udp_listen.go#L57)):*
> ```Go
> 	ReadFromVia(b []byte) (int, UDPAddr, *Path, error)
> 	// WriteToWithCtx writes a message to the remote address using a path from
> 	// the path selector. ctx is passed to the path selector.
> ```

Similar comment to the counterpart function in  `udp_dial.go`
___
*[`pkg/pan/udp_listen.go` line 180 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgqaD13CF8pAXoKpW:-OCXgqaD13CF8pAXoKpX:bmm82js) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/udp_listen.go#L180)):*
> ```Go
> }
> 
> func (s *DefaultReplySelector) Path(ctx interface{}, remote UDPAddr) *Path {
> ```

_ (unused parameter)



_Code quote:_
```Go
ctx
```
___
*[`pkg/pan/sciond.go` line 52 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXY9Rb1N1uTVUYbSGi:-OCXY9Rb1N1uTVUYbSGj:b32v1y) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/sciond.go#L52)):*
> ```Go
> 
> func (e HostContextError) Error() string {
> 	return fmt.Sprintf("error initializing SCION host context: '%s'", e.Cause)
> ```

%v



_Code quote:_
```Go
%s
```
___
*[`pkg/pan/path.go` line 47 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXa41e5kgzbzaNsjIA:-OCXa41e5kgzbzaNsjIB:b-o0w6ad) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/path.go#L47)):*
> ```Go
> }
> 
> // DataplaneLen returns the legnth of the path in the data plane.
> ```

length



_Code quote:_
```Go
legnth
```
___
*[`pkg/pan/path.go` line 48 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXRY8_D6PMBmiyDndx:-OCXRY8_D6PMBmiyDndy:b-fnvqdt) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/path.go#L48)):*
> ```Go
> 
> // DataplaneLen returns the legnth of the path in the data plane.
> func (p *Path) DataplaneLen() (int, error) {
> ```

Currently this function isn't used anywhere, could we add some small UT?
___
*[`ssh/client/ssh/selector.go` line 58 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgs3c7HRan1FDXPsB:-OCXgs3c7HRan1FDXPsC:bmm82js) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/ssh/client/ssh/selector.go#L58)):*
> ```Go
> }
> 
> func (s *roundRobinSelector) Path(cts interface{}) *pan.Path {
> ```

_ (unused parameter)



_Code quote:_
```Go
cts
```
___
*[`ssh/client/ssh/selector.go` line 97 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgtHT1u2ELazIWIsE:-OCXgtHT1u2ELazIWIsF:bmm82js) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/ssh/client/ssh/selector.go#L97)):*
> ```Go
> }
> 
> func (s *randomSelector) Path(ctx interface{}) *pan.Path {
> ```

_ (unused parameter)



_Code quote:_
```Go
ctx
```
___
*[`pkg/pan/selector.go` line 34 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXdww66UO2j8_XrFGn:-OCXdww66UO2j8_XrFGo:b81zjpv) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L34)):*
> ```Go
> 	// Path selects the path for the next packet.
> 	// Invoked for each packet sent with Write.
> 	Path(ctx interface{}) *Path
> ```

Is there a reason for not making this "context.Context"



_Code quote:_
```Go
interface{}
```
___
*[`pkg/pan/selector.go` line 67 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXeURy4mfd3p0PN2qn:-OCXeURy4mfd3p0PN2qo:bmm82js) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L67)):*
> ```Go
> }
> 
> func (s *DefaultSelector) Path(ctx interface{}) *Path {
> ```

_ (unused parameter)



_Code quote:_
```Go
ctx
```
___
*[`pkg/pan/selector.go` line 146 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXeYsW1AAm1tRnfLPK:-OCXeYsW1AAm1tRnfLPL:bmm82js) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L146)):*
> ```Go
> }
> 
> func (s *PingingSelector) Path(ctx interface{}) *Path {
> ```

_ (unused parameter)



_Code quote:_
```Go
ctx
```
___
*[`pkg/pan/udp_dial.go` line 32 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXf30xCBegI0BHoq7t:-OCXf30xCBegI0BHoq7u:b-qso58e) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/udp_dial.go#L32)):*
> ```Go
> 	SetPolicy(policy Policy)
> 	// WriteWithCtx writes a message to the remote address using a path from the
> 	// path policy and selector. ctx is passed to the path selector.
> ```

It may be useful to extend this comment with the brief explanation you have added to this PR,i.e.,: "he context can provide additional information, e.g., whether the packet is urgent or not.", or a similar one.


<!-- Sent from Reviewable.io -->

2024-12-07 18:48 UTC, lschulz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/260)* status: 4 of 11 files reviewed, 11 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/pan/path.go` line 47 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXa41e5kgzbzaNsjIA:-ODWYtRUEzGSqwUEHQNK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/path.go#L47)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

length
</blockquote></details>

Done.
___
*[`pkg/pan/path.go` line 48 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXRY8_D6PMBmiyDndx:-ODWYwwT9HsA1T2Gj-lP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/path.go#L48)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Currently this function isn't used anywhere, could we add some small UT?
</blockquote></details>

Done.
___
*[`pkg/pan/sciond.go` line 52 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXY9Rb1N1uTVUYbSGi:-ODWcw_XAY9YTi3KHDos:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/sciond.go#L52)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

%v
</blockquote></details>

Done.
___
*[`pkg/pan/selector.go` line 34 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXdww66UO2j8_XrFGn:-ODWZ1RdBmb8YRv2_ZBT:bske8) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L34)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Is there a reason for not making this "context.Context"
</blockquote></details>

I thought about making it a context.Context, but I didn't see a reason to restrict user code to a specific type or interface. That being said, I'm not against using context.Context if this is more idiomatic, or if PAN would need to interact with this context in the future.
___
*[`pkg/pan/selector.go` line 67 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXeURy4mfd3p0PN2qn:-ODWaxLzBr7YvCAfRg67:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L67)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

_ (unused parameter)
</blockquote></details>

Done.
___
*[`pkg/pan/selector.go` line 146 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXeYsW1AAm1tRnfLPK:-ODWb4Hd4MAHCiNWS4tO:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L146)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

_ (unused parameter)
</blockquote></details>

Done.
___
*[`pkg/pan/udp_dial.go` line 32 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXf30xCBegI0BHoq7t:-ODWbssFBfY3QTjN-lb0:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/udp_dial.go#L32)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

It may be useful to extend this comment with the brief explanation you have added to this PR,i.e.,: "he context can provide additional information, e.g., whether the packet is urgent or not.", or a similar one.
</blockquote></details>

Done.
___
*[`pkg/pan/udp_listen.go` line 57 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgX4S0vRXujwcMY3-:-ODWc8kr2vOuRTw_n-4o:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/udp_listen.go#L57)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Similar comment to the counterpart function in  `udp_dial.go`
</blockquote></details>

Done.
___
*[`pkg/pan/udp_listen.go` line 180 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgqaD13CF8pAXoKpW:-ODWcF6998xRfUSMVc7w:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/udp_listen.go#L180)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

_ (unused parameter)
</blockquote></details>

Done.
___
*[`ssh/client/ssh/selector.go` line 58 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgs3c7HRan1FDXPsB:-ODWcSTwA7AozFT_YeEk:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/ssh/client/ssh/selector.go#L58)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

_ (unused parameter)
</blockquote></details>

Done.
___
*[`ssh/client/ssh/selector.go` line 97 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXgtHT1u2ELazIWIsE:-ODWcSrb9HGl_7TUpkXW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/ssh/client/ssh/selector.go#L97)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

_ (unused parameter)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-09 14:57 UTC, JordiSubira requested changes
> Reviewed 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/260)* status: 7 of 11 files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/pan/selector.go` line 34 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXdww66UO2j8_XrFGn:-ODfue0e3SdURiXrOgBf:b3y3bve) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L34)):*
<details><summary><i>Previously, lschulz (Lars-Christian Schulz) wrote…</i></summary><blockquote>

I thought about making it a context.Context, but I didn't see a reason to restrict user code to a specific type or interface. That being said, I'm not against using context.Context if this is more idiomatic, or if PAN would need to interact with this context in the future.
</blockquote></details>

I do believe it is more idiomatic and more consistent with the existing code which uses `context.Context`, so if there's no strong reason, I'd opt for using it here as well.


<!-- Sent from Reviewable.io -->

2024-12-14 22:25 UTC, lschulz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/260)* status: 5 of 11 files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/pan/selector.go` line 34 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-OCXdww66UO2j8_XrFGn:-OE6FbREEMMiA4f8MaI5:b-xq10la) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/e98b1b8ba8e51dbb659e22c1983bd76d807be2ec/pkg/pan/selector.go#L34)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I do believe it is more idiomatic and more consistent with the existing code which uses `context.Context`, so if there's no strong reason, I'd opt for using it here as well.
</blockquote></details>

Ok, I switched to context.Context.


<!-- Sent from Reviewable.io -->

2024-12-16 08:32 UTC, JordiSubira approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/260#-:-OEDaH2wAzNwYWGEqdOy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-02-28 13:36 UTC, JordiSubira approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/260)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-02-28 13:39 UTC, merged